export const PATTERN = {
  VERIFY_AUTH: 'VERIFY_AUTH',
};

export const Server = {
  SERVER_PORT: 'SERVER_PORT',
};

export const AuthService = {
  AUTH_SERVICE: 'AUTH_SERVICE',
  AUTH_SERVICE_HOST: 'AUTH_SERVICE_HOST',
  AUTH_SERVICE_PORT: 'AUTH_SERVICE_PORT',
  AUTH_SERVICE_TRANSPORT_PORT: 'AUTH_SERVICE_TRANSPORT_PORT',
};

export const ChatService = {
  CHAT_SERVICE: 'CHAT_SERVICE',
  CHAT_SERVICE_HOST: 'CHAT_SERVICE_HOST',
  CHAT_SERVICE_PORT: 'CHAT_SERVICE_PORT',
  CHAT_SERVICE_TRANSPORT_PORT: 'CHAT_SERVICE_TRANSPORT_PORT',
};
