export class UserReq {
  id: number;
}

export const AuthService = {
  AUTH_SERVICE: 'AUTH_SERVICE',
  AUTH_SERVICE_HOST: 'AUTH_SERVICE_HOST',
  AUTH_SERVICE_PORT: 'AUTH_SERVICE_PORT',
  AUTH_SERVICE_TRANSPORT_PORT: 'AUTH_SERVICE_TRANSPORT_PORT',
};
